-- AlterTable
ALTER TABLE "Food" ALTER COLUMN "quantity_value" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "carbohydrate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fat" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "protein" SET DATA TYPE DOUBLE PRECISION;
